-- Stage 1: Customer/account reference data used to enrich transaction and alert views.
CREATE TABLE customers (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    acc_num VARCHAR(255) UNIQUE,
    acc_type VARCHAR(50),
    bank_name VARCHAR(255),
    currency VARCHAR(3)
);

-- Stage 2: Raw transaction stream retained for rule evaluation and audit.
CREATE TABLE transactions (
    txn_id VARCHAR(255) PRIMARY KEY,
    timestamp TIMESTAMP,
    amount DECIMAL(15, 2),
    currency VARCHAR(3), -- Either GBP, INR, USD, EUR
    payee_acc_num VARCHAR(255),
    payer_acc_num VARCHAR(255),
    status VARCHAR(50),
    type VARCHAR(50)
);

-- Stage 3: Alerts generated by risk rules.
CREATE TABLE alerts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    status VARCHAR(50),
    severity_score INT,
    txn_id VARCHAR(255),
    alert_timestamp TIMESTAMP,
    CONSTRAINT fk_alert_txn FOREIGN KEY (txn_id) REFERENCES transactions(txn_id),
    rule_ids VARCHAR(255)
);

-- Stage 4: Status transition history for analyst actions.
CREATE TABLE alert_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    alert_id BIGINT,
    comment VARCHAR(255),
    status VARCHAR(50),
    log_timestamp TIMESTAMP,
    CONSTRAINT fk_alert_log_alert FOREIGN KEY (alert_id) REFERENCES alerts(id)
);

-- Indexes to keep list/detail alert queries responsive as data grows.
CREATE INDEX idx_alert_status_ts ON alerts(status, alert_timestamp);
CREATE INDEX idx_alert_log_alert_ts ON alert_log(alert_id, log_timestamp);
CREATE INDEX idx_txn_payer_ts ON transactions(payer_acc_num, timestamp);