-- Stage 1: Customer/account reference data used to enrich transaction and alert views.
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    acc_num VARCHAR(255) NOT NULL UNIQUE,
    acc_type VARCHAR(50),
    bank_name VARCHAR(255),
    currency VARCHAR(3)
);

-- Stage 2: Raw transaction stream retained for rule evaluation and audit.
CREATE TABLE IF NOT EXISTS transactions (
    txn_id VARCHAR(255) PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    amount DECIMAL(15, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL, -- USD, GBP, INR, EUR
    payee_acc_num VARCHAR(255) NOT NULL,
    payer_acc_num VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    type VARCHAR(50) NOT NULL
);

-- Stage 3: Alerts generated by risk rules.
CREATE TABLE IF NOT EXISTS alerts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    status VARCHAR(50) NOT NULL, -- OPEN, ACKNOWLEDGED, INVESTIGATING, DISMISSED, CLOSED
    severity_score INT NOT NULL,
    txn_id VARCHAR(255) NOT NULL,
    alert_timestamp TIMESTAMP NOT NULL,
    rule_ids VARCHAR(255) NOT NULL, -- Comma-separated (e.g., "1,2,4")
    CONSTRAINT fk_alert_txn FOREIGN KEY (txn_id) REFERENCES transactions(txn_id)
);

-- Stage 4: Status transition history for analyst actions.
CREATE TABLE IF NOT EXISTS alert_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    alert_id BIGINT NOT NULL,
    comment VARCHAR(500) NOT NULL,
    status VARCHAR(50) NOT NULL,
    log_timestamp TIMESTAMP NOT NULL,
    CONSTRAINT fk_alert_log_alert FOREIGN KEY (alert_id) REFERENCES alerts(id)
);

-- Indexes to keep list/detail alert queries responsive as data grows.
SET @idx_alert_status_ts := (
    SELECT IF(
        EXISTS(
            SELECT 1
            FROM information_schema.statistics
            WHERE table_schema = DATABASE()
              AND table_name = 'alerts'
              AND index_name = 'idx_alert_status_ts'
        ),
        'SELECT 1',
        'CREATE INDEX idx_alert_status_ts ON alerts(status, alert_timestamp)'
    )
);
PREPARE stmt FROM @idx_alert_status_ts;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @idx_alert_log_alert_ts := (
    SELECT IF(
        EXISTS(
            SELECT 1
            FROM information_schema.statistics
            WHERE table_schema = DATABASE()
              AND table_name = 'alert_log'
              AND index_name = 'idx_alert_log_alert_ts'
        ),
        'SELECT 1',
        'CREATE INDEX idx_alert_log_alert_ts ON alert_log(alert_id, log_timestamp)'
    )
);
PREPARE stmt FROM @idx_alert_log_alert_ts;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @idx_txn_payer_ts := (
    SELECT IF(
        EXISTS(
            SELECT 1
            FROM information_schema.statistics
            WHERE table_schema = DATABASE()
              AND table_name = 'transactions'
              AND index_name = 'idx_txn_payer_ts'
        ),
        'SELECT 1',
        'CREATE INDEX idx_txn_payer_ts ON transactions(payer_acc_num, timestamp)'
    )
);
PREPARE stmt FROM @idx_txn_payer_ts;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;