package org.ByteWatch.model;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Represents a fraud/risk alert generated by the rule engine, as
 * stored in the {@code alerts} table. {@code ruleIds} is persisted
 * as a comma-separated string (e.g. "1,2,4") but exposed to callers
 * as a {@code List<Integer>} for convenience.
 */
public class alert {

    private Long id;
    private String status;        // OPEN, ACKNOWLEDGED, INVESTIGATING, DISMISSED, CLOSED
    private int severityScore;
    private String txnId;
    private LocalDateTime alertTimestamp;
    private String ruleIds;       // comma-separated, e.g. "1,2,4"

    public alert() {
    }

    public alert(Long id, String status, int severityScore, String txnId,
                 LocalDateTime alertTimestamp, String ruleIds) {
        this.id = id;
        this.status = status;
        this.severityScore = severityScore;
        this.txnId = txnId;
        this.alertTimestamp = alertTimestamp;
        this.ruleIds = ruleIds;
    }

    /**
     * Builds the comma-separated {@code ruleIds} string from a list of
     * triggered rule IDs. Convenience factory used by the rule engine.
     */
    public static String toRuleIdsString(List<Integer> ruleIds) {
        return ruleIds.stream()
                .map(String::valueOf)
                .collect(Collectors.joining(","));
    }

    /**
     * Parses the stored comma-separated {@code ruleIds} string back
     * into a list of integers. Returns an empty list if blank.
     */
    public List<Integer> getRuleIdsAsList() {
        if (ruleIds == null || ruleIds.isBlank()) {
            return List.of();
        }
        return Arrays.stream(ruleIds.split(","))
                .map(String::trim)
                .map(Integer::parseInt)
                .collect(Collectors.toList());
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public int getSeverityScore() {
        return severityScore;
    }

    public void setSeverityScore(int severityScore) {
        this.severityScore = severityScore;
    }

    public String getTxnId() {
        return txnId;
    }

    public void setTxnId(String txnId) {
        this.txnId = txnId;
    }

    public LocalDateTime getAlertTimestamp() {
        return alertTimestamp;
    }

    public void setAlertTimestamp(LocalDateTime alertTimestamp) {
        this.alertTimestamp = alertTimestamp;
    }

    public String getRuleIds() {
        return ruleIds;
    }

    public void setRuleIds(String ruleIds) {
        this.ruleIds = ruleIds;
    }
}
